@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}

GET {{host}}

###
POST {{host}}/api/user
content-Type: application/json

{
    "name": "Roman",
    "email": "zrhdik111",
    "password": "Pa$sw0rd"
}

###
POST {{host}}/api/user/login
Content-Type: application/json

{
    "email": "zrhdik111",
    "password": "Pa$sw0rd"
}