@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}

@token =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUk9NQU4iLCJlbWFpbCI6IkVNQUlsMTEiLCJpbWFnZSI6Imh0dHBzOi8vaWgxLnJlZGJ1YmJsZS5uZXQvaW1hZ2UuMTA0NjM5MjI5Mi4zMzQ2L3N0LG1lZGl1bSw1MDd4NTA3LXBhZCw2MDB4NjAwLGY4ZjhmOC5qcGciLCJpZCI6MTIzLCJpYXQiOjE3MDM4MzA2MDgsImV4cCI6MTcwMzgzMTIwOH0.HphyNF9LCJE1x1BB0Wwe_Vi3_5KnGZiSs1ODcFy-0NI


GET {{host}}

###
POST {{host}}/api/users
content-Type: application/json

{
    "name": "ROMAN",
    "email": "EMAIl11",
    "password": "Pa$sw0rd"
}

###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "EMAIl11",
    "password": "FLASKLFWEs2!"
}

###
GET {{host}}/api/users
Authorization: Bearer {{token}}

###
PUT {{host}}/api/users/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "password":"FLASKLFWEs2!"
}

###
PUT {{host}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "image": "image",
    "password":"FLASKLF"
}