@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}

GET {{host}}

###

GET {{host}}/api/v1/items

###
POST {{host}}/api/user
content-Type: application/json

{
    "name": "ROMAN",
    "email":"a",
    "password":"PaS$W0RD"
}

###
GET {{host}}/api/user
content-Type: application/json

{
    "email":"a",
    "password":"PaS$W0RD"
}




