name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test:ci
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm run lint && npm run test