name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_SERVER_IP: ${{ secrets.SSH_SERVER_IP }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USERNAME }}@${{ env.SSH_SERVER_IP }} << 'EOF'
          cd /home/deploy/eazyeaze/MeditationNotMedication
          git pull
          pm2 restart 2
        EOF
